#!/bin/bash

cat - | grep '^#' | node -e "

    var fs = require('fs');
    var chunks = '';

    process.stdin.resume();
    process.stdin.setEncoding('utf8');

    process.stdin.on('data', function(chunk) {
        chunks += chunk;
    });

    process.stdin.on('end', function() {

        var lastLength = 0;
        var curTree    = [];
        var content    = fs.readFileSync('${1}', 'utf8');

        chunks.split('\n').forEach(function(line) {

            if ('' == line) {
                return;
            }

            var head      = line.match(/^(#*)\s(.*)$/i);
            var headText  = head[2].replace(/[^a-z0-9]/ig, '-')
                                   .replace(/-+/gi, '-');
            var curLenght = head[1].length - 1;

            if (lastLength > curLenght) {
                curTree = curTree.slice(0, curLenght);
            }

            curTree[curLenght] = headText.toLowerCase();
            lastLength = curLenght;

            var slug = curTree.join('/');

            var heading = line.replace(/\(/g, '\\\(')
                              .replace(/\)/g, '\\\)')
                              .replace(/\[/g, '\\\[')
                              .replace(/\]/g, '\\\]')
                              .replace(/\"/g, '\\\"')
                              .replace(/\./g, '\\\.');

            content = content.replace(
                new RegExp('^' + heading + '\$', 'mgi'),
                line
                + '<a name=\"' + slug + '\"></a>'
                + ' <a class=\"toc-humanized-anchor\" href=\"#' + slug + '\">&para;</a>'
            );
        });

        fs.writeFileSync('${1}', content);
    });
"

